-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1004640
-- Name: FINAL FANTASY TACTICS - The Ivalice Chronicles
-- Updated: April 17, 2026 at 10:55:39 PM UTC
-- FINAL FANTASY TACTICS - The Ivalice Chronicles
-- Created: March 16, 2026 at 13:23:21 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 2

-- MAIN APPLICATION
addappid(1004640, 1, "bd74df1e233ffd3920f8bbf8fe4dc604f0793b026dea9d94c6ea296b7b8df896") -- FINAL FANTASY TACTICS - The Ivalice Chronicles
-- MAIN APP DEPOTS
addappid(1004641, 1, "b9ffdc9182829343bcdf50e8c3fe66b2fc58fbbe11980078cfc04e6f8d91701d") -- Depot 1004641
setManifestid(1004641, "3840235392788841032", 10951253527)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3589750) -- FINAL FANTASY TACTICS - The Ivalice Chronicles Pre-order Bonuses
addappid(3589760) -- FINAL FANTASY TACTICS - The Ivalice Chronicles Deluxe Edition Bonuses
