-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1172650
-- Name: INDUSTRIA
-- Updated: May 4, 2026 at 05:16:27 PM UTC
-- INDUSTRIA
-- Created: September 29, 2025 at 19:07:05 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 3
-- Total DLCs: 0
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(1172650) -- INDUSTRIA
-- MAIN APP DEPOTS
addappid(1172651, 1, "17a7c09d7a646cc91072b4e15f029588f55a45d69e7d9d58d34c7b61442a19d8") -- Industria Content
setManifestid(1172651, "4677057679280728670", 9479457963)
-- SHARED DEPOTS (from other apps)
addappid(228988, 1, "1845444d5e2cfd0ae65ae4a8fedb6e2fbf776fcc5b913ab4ac461bc9a74f8358") -- VC 2019 Redist (Shared from App 228980)
setManifestid(228988, "6645201662696499616", 29212173)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
