-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1290760
-- Name: Gecko Gods
-- Updated: April 16, 2026 at 04:40:27 PM UTC
-- Gecko Gods
-- Created: April 16, 2026 at 12:18:56 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(1290760) -- Gecko Gods
-- MAIN APP DEPOTS
addappid(1290761, 1, "09296ac59aa67605bc27389f12111c011e001a409679a0e868d00a4c89016d9c") -- Depot 1290761
setManifestid(1290761, "8957001337333059047", 3752577241)
