-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1319420
-- Name: Chasing Static
-- Updated: May 4, 2026 at 03:04:07 PM UTC
-- Chasing Static
-- Created: October 02, 2025 at 12:24:47 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(1319420) -- Chasing Static
-- MAIN APP DEPOTS
addappid(1319421, 1, "d3ea530f99ab544eafcbbfea112f319ca8159705e105060380dd98cdebc1da02") -- Echo Vale Content
setManifestid(1319421, "85530379018513849", 985794107)
