-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1663850
-- Name: REPLACED
-- Updated: April 16, 2026 at 07:23:50 PM UTC
-- REPLACED
-- Created: April 15, 2026 at 11:00:31 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(1663850) -- REPLACED
-- MAIN APP DEPOTS
addappid(1663851, 1, "6c5ad07d24ba971709a2773ed2263ddc46bf21f9a2608989ef9438668db72760") -- Depot 1663851
setManifestid(1663851, "5809737195448627651", 5942037148)
