-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1714320
-- Name: Find Love or Die Trying
-- Updated: May 8, 2026 at 12:54:11 PM UTC
-- Find Love or Die Trying
-- Created: January 19, 2026 at 15:00:08 EST
-- Website: https://hubcapmanifest.com/
-- Total Depots: 11
-- Total DLCs: 1

-- MAIN APPLICATION
addappid(1714320, 1, "03fddd32a2d71828b423fcff94d392dc6be24cdd6ab5d0fe60ca5f15bdc563b2") -- Find Love or Die Trying
-- MAIN APP DEPOTS
addappid(1714321, 1, "fd4d9b078b1327a6c7f5e809ace34e3c4b92f2d474be7589efa475cc8893c406") -- Depot 1714321
setManifestid(1714321, "5848282827748410911", 1019977443)
addappid(1714322, 1, "1daed46d91cc7dc787156e43c8d26e8f27c8431399645599576ec015d3e1aa27") -- Depot 1714322
setManifestid(1714322, "3018866352746197530", 1021183526)
addappid(1714323, 1, "40cc5cf1555f8129e260fef94897ba39b4d5e6572332c4079e484ef6ac3c0c3e") -- Depot 1714323
setManifestid(1714323, "7369314699922443198", 1020779645)
addappid(1714325, 1, "c3710481924448208513b4a861d144f93eb07dad694e06d45b7754005be26bdd") -- Depot 1714325
setManifestid(1714325, "7264566319349524686", 1025788726)
addappid(1714326, 1, "15ccca6211a0cf810b73755fc87175ad61c0e8448e712a91ca98e2f443fb2f6e") -- Depot 1714326
setManifestid(1714326, "6089756108171565899", 1020134221)
addappid(1714327, 1, "e20aa8ade0f77866e4af8ca4bac485b1e8ee987de5baa23448a49c5cc3987475") -- Depot 1714327
setManifestid(1714327, "7201881682035241585", 1579456982)
addappid(1714328, 1, "2998872738470603d91b2ee700d47714f7458f5b918cabc8369f0d8a11571305") -- Depot 1714328
setManifestid(1714328, "8418328703748345940", 1579456982)
addappid(1714329, 1, "a4b969538f36ab950cc5a6fd9072d7d353b03faa5ce59b86de096c04c5bdc4ee") -- Depot 1714329
setManifestid(1714329, "175275881294664136", 1579456982)
addappid(1714324, 1, "37895d446173238d7fe119eedf724bc61734812596dbe76f128356dbf2d39e42") -- Depot 1714324
setManifestid(1714324, "5411597587493942832", 1639714872)
addappid(1714331, 1, "ebd7ef6bd22d4111fa43a228ca64c2149c1f4f9a63a7450ccc1d07cd5bb13fe9") -- Depot 1714331
setManifestid(1714331, "5322361907025582106", 1639714872)
-- DLCS WITH DEDICATED DEPOTS
-- Find Love or Die Trying Fan Pack (AppID: 1714330)
addappid(1714330)
addappid(1714330, 1, "ddd162f0b5aff18bd29f54fa3350c8246a1b2817552057307d6b4e57e76db4e9") -- Find Love or Die Trying Fan Pack - Depot 1714330
setManifestid(1714330, "252240704836753468", 927044189)
