-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 1761390
-- Name: Hatsune Miku: Project DIVA Mega Mix+
-- Updated: May 3, 2026 at 08:20:22 PM UTC
-- Hatsune Miku: Project DIVA Mega Mix+
-- Created: September 29, 2025 at 16:54:27 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 7
-- Total DLCs: 2

-- MAIN APPLICATION
addappid(1761390) -- Hatsune Miku: Project DIVA Mega Mix+
-- MAIN APP DEPOTS
addappid(1761391, 1, "8956256443c8c0ed28f554d5d6a72071a4fc3d43fb7b78390caccf06371ec020") -- Depot 1761391
setManifestid(1761391, "4232859259494611954", 24635083328)
addappid(1761393, 1, "1194270c62e1dfef04eb3501ecfc1a6008788b28fe4077ad54d4ec253611f131") -- Depot 1761393
setManifestid(1761393, "54992195187667300", 617092584)
addappid(1761392, 1, "c9a7efab34de70d5b335212e474e5cea3578ee3aae859ac15f83bb031b6844d2") -- Depot 1761392
setManifestid(1761392, "2790283740545487649", 135164728)
addappid(1761394, 1, "95528549686ea66125e033ab5ab1e124d287aa9cfb40150fca1216de31d23f17") -- Depot 1761394
setManifestid(1761394, "4280363553513963279", 483263688)
-- DLCS WITH DEDICATED DEPOTS
-- Hatsune Miku Project DIVA Mega Mix Extra Song Pack (AppID: 1887030)
addappid(1887030)
addappid(1887030, 1, "1a73480caec7f6d497c144bba7e2373a578d6ef7d0e5202a3738755309e19f54") -- Hatsune Miku Project DIVA Mega Mix Extra Song Pack - Depot 1887030
setManifestid(1887030, "3785652973440637976", 9580780048)
addappid(1887031, 1, "c84abd97b31306f57b9cbd92e88916ac4dae624692ca99daf0e71d502ca3c056") -- Hatsune Miku Project DIVA Mega Mix Extra Song Pack - Depot 1887031
setManifestid(1887031, "5494193333052898626", 378331632)
addappid(1887032, 1, "5fa6cf8eacef05422c9e30bb2a0c5f6623303261db3aaeba85f5111a6e8bbe8c") -- Hatsune Miku Project DIVA Mega Mix Extra Song Pack - Depot 1887032
setManifestid(1887032, "6082831898246119726", 624816)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(1905750) -- Hatsune Miku Project DIVA Mega Mix Item Unlock Key
