-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 2564520
-- Name: Lost in Random: The Eternal Die
-- Updated: April 17, 2026 at 10:56:27 PM UTC
-- Lost in Random: The Eternal Die
-- Created: October 30, 2025 at 01:11:38 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 2
-- Total DLCs: 4

-- MAIN APPLICATION
addappid(2564520) -- Lost in Random: The Eternal Die
-- MAIN APP DEPOTS
addappid(2564521, 1, "4b679f8c7ffc59c1398369a7bb72987e78717c22d81ec186eb11bb0cc0e5f6e8") -- Depot 2564521
setManifestid(2564521, "7761962271429986850", 3840580023)
-- DLCS WITH DEDICATED DEPOTS
-- Lost in Random The Eternal Die - Artbook (AppID: 3478380)
addappid(3478380)
addappid(3478380, 1, "08b4f767f1591c4c96ec034dd7c78d0d442ac1d6c39586fff1ece5f94a7e4e6c") -- Lost in Random The Eternal Die - Artbook - Depot 3478380
setManifestid(3478380, "8781692662282280762", 251201091)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3573930) -- Lost In Random The Eternal Die - Wardrobe Expansion
addappid(3857960) -- Lost in Random The Eternal Die - Stitched in Style
addappid(4040310) -- Lost in Random The Eternal Die - Cursed Couture
