-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3100370
-- Name: Black Jacket
-- Updated: May 12, 2026 at 06:09:07 PM UTC
-- Black Jacket
-- Created: May 12, 2026 at 14:07:08 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 1

-- MAIN APPLICATION
addappid(3100370) -- Black Jacket
-- MAIN APP DEPOTS
addappid(3100371, 1, "6f520af8fe511bdc08ff85343a4c6976c94bea0213dd877ab716758d5813cb2b") -- Depot 3100371
setManifestid(3100371, "6413155425808314925", 3193589333)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(4635860) -- Supporter Pack
