-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3293010
-- Name: Easy Delivery Co.
-- Updated: May 1, 2026 at 05:47:55 PM UTC
-- Easy Delivery Co.
-- Created: November 30, 2025 at 14:55:48 EST
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(3293010) -- Easy Delivery Co.
-- MAIN APP DEPOTS
addappid(3293011, 1, "8e652df7f7f499154c4db62e26560d348c9528c9a516d8095f23c33eaf858b27") -- Depot 3293011
setManifestid(3293011, "3989692418221166142", 498434769)
