-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 3500390
-- Name: Mega Man Star Force Legacy Collection
-- Updated: April 17, 2026 at 10:56:55 PM UTC
-- Mega Man Star Force Legacy Collection
-- Created: March 29, 2026 at 07:20:10 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 4
-- Total DLCs: 2
-- Shared Depots: 1

-- MAIN APPLICATION
addappid(3500390, 1, "ce78d0d31240d39462ce0f1ec89e60b7d5cbe3266c80a66681a647a59491ab02") -- Mega Man Star Force Legacy Collection
-- MAIN APP DEPOTS
addappid(3500391, 1, "febf6d8948ae4c2e1a199fa36f58cbfd6c5b3d81c130a612604f803316f5326b") -- Depot 3500391
setManifestid(3500391, "4414609150574936853", 5693978069)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
-- DLCS WITH DEDICATED DEPOTS
-- Mega Man Star Force Legacy Collection  Geo Stelar and Omega-Xis Character Model Pack (AppID: 4059840)
addappid(4059840)
addappid(4059840, 1, "e36991eb8125945b9f99b2c11323010a5a918ad3f07b8bb7dc199a5cb4c49b42") -- Mega Man Star Force Legacy Collection  Geo Stelar and Omega-Xis Character Model Pack - Depot 4059840
setManifestid(4059840, "2274394409022129768", 50345033)
-- Mega Man Star Force Legacy Collection  Sonia Strumm and Luna Platz Character Model Pack (AppID: 4059860)
addappid(4059860)
addappid(4059860, 1, "a4a1b191f1d28dd691f0e9197d0f156a0781b407a466d44a7e455aa97903b032") -- Mega Man Star Force Legacy Collection  Sonia Strumm and Luna Platz Character Model Pack - Depot 4059860
setManifestid(4059860, "1976583030948263159", 16410091)
-- EMPTY DEPOTS (no content on any branch)
-- addappid(4390970) -- Depot 4390970 (empty depot)
