-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 4007340
-- Name: Skinfreak
-- Updated: April 25, 2026 at 02:41:32 PM UTC
-- Skinfreak
-- Created: October 27, 2025 at 19:25:33 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(4007340) -- Skinfreak
-- MAIN APP DEPOTS
addappid(4007341, 1, "0802543bf60d688f3c7cf00c3b37789be740aa31ed58b3e89d610cb9d93d3745") -- Depot 4007341
setManifestid(4007341, "6079576131007371025", 1418334370)
