-- =========================================================
--  This file was generated by SB manifest.
--  No one has the right to distribute or take credit for this file.
--  Personal use and sharing with friends is allowed.
--  Owner: SB
-- =========================================================
-- Generated Lua Manifest by SB manifest
-- AppID 4161970
-- Name: Let It Consume
-- Updated: April 16, 2026 at 12:00:59 AM UTC
-- Let It Consume
-- Created: April 15, 2026 at 11:22:50 EDT
-- Website: https://hubcapmanifest.com/
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(4161970) -- Let It Consume
-- MAIN APP DEPOTS
addappid(4161971, 1, "5a7f047fe57569c87d762d4b95dabea73f04519221ac6ca3a576d2876591e074") -- Depot 4161971
setManifestid(4161971, "6582972890387257077", 137082184)
